# Generated by Django 5.0.6 on 2024-06-07 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionlog",
            name="actual_output",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productionlog",
            name="availability",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productionlog",
            name="good_products",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productionlog",
            name="ideal_cycle_time",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="productionlog",
            name="oee",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productionlog",
            name="performance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productionlog",
            name="quality",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productionlog",
            name="total_products",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productionlog",
            name="unplanned_downtime",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name="productionlog",
            name="end_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="productionlog",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
